ArklyShop/ArklyShop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('showcase/', include('showcase.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ArklyShop/showcase/urls.py
from django.urls import path
from . import views


app_name = 'showcase'
urlpatterns = [
    path('', views.index, name='index'),
    path('item/<slug:slug>/', views.DetailView.as_view(), name='detail'),
    path('create/', views.ddformview, name='create'),
]

ArklyShop/showcase/models.py
from django.db import models
from django.urls import reverse

ascending_price = 'AP'  # Sorting options
descending_price = 'DP'
ascending_relevance = 'AR'
descending_relevance = 'DR'
ascending_date = 'AD'
descending_date = 'DD'
soring_choices = [
    (ascending_price, 'ascending_price'),
    (descending_price, 'descending_price'),
    (ascending_relevance, 'ascending_relevance'),
    (descending_relevance, 'descending_relevance'),
    (ascending_date, 'ascending_date'),
    (descending_date, 'descending_date')
]


class Stock(models.Model):
    name = models.CharField(max_length=30)
    slug = models.SlugField(null=True)
    sort = models.CharField(max_length=20, choices=soring_choices, default='DP')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('showcase', kwargs={'slug': self.slug})


class Item(models.Model):
    name = models.CharField(max_length=20)
    price = models.IntegerField()
    date = models.DateTimeField('date published', default=None)
    relevance = models.SmallIntegerField(default=0)
    image = models.ImageField(upload_to='upload/')
    type = models.CharField(max_length=20)
    size = models.CharField(max_length=4)
    quantity = models.SmallIntegerField()
    is_available = models.BooleanField()
    description = models.CharField(max_length=1000)
    stock = models.ForeignKey(Stock, on_delete=models.PROTECT)  # A stock should not be deleted as long as it has items
    slug = models.SlugField(null=True, unique=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('showcase', kwargs={'slug': self.slug})

ArklyShop/showcase/forms.py
from django import forms
from . import models


class DDMenuForm(forms.ModelForm):
    class Meta:
        model = models.Stock
        fields = ['sort']

ArklyShop/showcase/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views import generic
from .models import Item, Stock
from .forms import DDMenuForm


def index(request):
    main_stock = Stock.objects.get(name='Main')
    items = main_stock.item_set.all().order_by('price', '-name')
    length = len(items)

    context = {
        'items': items,
        'length': length,
    }
    return HttpResponse(render(request, 'showcase/index.html', context))


# class CreateMyModelView(generic.CreateView):
# model = Stock
# form_class = DDMenuForm
# template_name = 'showcase/index.html'
# success_url = 'showcase/detail.html'

def ddformview(request):
    stock = Stock.objects.get(name='Main')
    form = DDMenuForm(request.POST or None)
    if form.is_valid():
        form = DDMenuForm(request.POST, instance=stock)
        form.save()
    context = {
        'form': form,
        'method': stock.sort,
    }
    return render(request, 'showcase/create.html', context)


class DetailView(generic.DetailView):
    model = Item
    template_name = 'showcase/detail.html'

ArklyShop/showcase/templates/showcase/base.html
<!DOCTYPE html>
<html lang="en">
{%load static%}
<head>
    <meta charset="UTF-8">
    <title>Arkly</title>
    <link rel="stylesheet" type="text/css" href="{% static 'showcase/style.css' %}">
</head>
<body>
    {% block sorting %}

    {% endblock sorting %}

    {% block content %}

    {% endblock content %}
</body>
</html>

ArklyShop/showcase/templates/showcase/create.html
{% extends 'showcase/index.html' %}

{% block sorting %}
<h1>Hey</h1>
<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="save">

</form>
<p>{{method}}</p>
{% endblock sorting %}

ArklyShop/showcase/templates/showcase/detail.html
{% extends 'showcase/base.html' %}

{% block content %}
<ul>
    <li><p>{{item.name}}</p></li>
    <li><p>{{item.description}}</p></li>
    <li><p>{{item.price}} $</p></li>
    <li><p>{{item.size}}</p></li>
    <li><p>{{item.is_available}}</p></li>
    <li><p>{{item.image}}</p></li>
    <li><img src="{{item.image.url}}" width="100px"/></li>
</ul>
{% endblock content %}

ArklyShop/showcase/templates/showcase/index.html
{% extends 'showcase/base.html' %}



{% block content %}

{% block sorting %}

{% endblock sorting %}

{% if length != 0 %}
<ul>
    {% for item in items %}
    <li><a href="{% url 'showcase:detail' item.name %}">{{item.name}}</a></li>
    {% endfor %}
</ul>
{% else %}
<p>Nothing to see here</p>
{% endif %}
{% endblock content %}